sudo: required
services:
  - docker

before_install:
  - docker build -t afcarl/docker-react -f Dockerfile.dev .

script:
  #- docker run afcarl/docker-react npm run test -- --coverage
  - docker run -e CI=true afcarl/docker-react npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-179989370246"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key_ID
  secret_access_key:
    secure: "$AWS_Secret_Access_Key"